collections:
  - name: community.docker
    version: 4.6.0
roles:
  - name: nvidia.nvidia_driver
    version: v2.3.0
    src: https://github.com/NVIDIA/ansible-role-nvidia-driver.git
  - name: geerlingguy.docker
    version: 7.4.7
    src: https://github.com/geerlingguy/ansible-role-docker.git
  - name: geerlingguy.pip
    version: 3.1.0
    src: https://github.com/geerlingguy/ansible-role-pip.git
